/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum Severity {
  LOW = "Low",
  MEDIUM = "Medium",
  HIGH = "High",
  CRITICAL = "Critical"
}

export enum IncidentStatus {
  ACTIVE = "Active",
  INVESTIGATING = "Investigating",
  CLOSED = "Closed"
}

export interface SecurityEvent {
  id: string;
  timestamp: string;
  sourceIp: string;
  destIp: string;
  user: string;
  host: string;
  eventType: string; // "Authentication", "NetworkConnection", "ProcessExecution", "FileAccess", "RegistryChange"
  severity: Severity;
  message: string;
  category: string; // "Auth", "Firewall", "Host", "Cloud", "Endpoint"
  score: number; // 0 - 100 raw threat score for this event
  matchedRuleId?: string;
  mitreTactic?: string;
  mitreTechnique?: string;
  mitreId?: string;
  details?: Record<string, any>;
}

export interface MitreMapping {
  tactic: string;
  technique: string;
  id: string;
}

export interface Incident {
  id: string;
  name: string;
  description: string;
  status: IncidentStatus;
  severity: Severity;
  score: number; // calculated threat score (0-100)
  timestamp: string;
  events: SecurityEvent[];
  mitreMapping: MitreMapping[];
  affectedEntities: {
    users: string[];
    hosts: string[];
  };
  attackStage: string; // "Initial Access", "Execution", "Lateral Movement", "Exfiltration", etc.
  automaticInvestigationStatus: "Pending" | "In Progress" | "Completed" | "Failed";
  aiInvestigationReport?: string; // Markdown generated by Gemini
  suggestedPlaybook?: string[];
}

export interface EntityBaseline {
  id: string; // username or hostname
  type: "User" | "Host";
  displayName: string;
  threatScore: number; // 0 - 100 overall threat level
  normalWorkHours: string; // e.g., "08:00 - 18:00"
  usualIps: string[];
  frequentActions: string[];
  anomaliesDetected: {
    timestamp: string;
    description: string;
    scoreContribution: number;
    mitreTechnique?: string;
  }[];
  department?: string; // for users
  operatingSystem?: string; // for hosts
  lastSeen: string;
}

export interface CorrelationRule {
  id: string;
  name: string;
  description: string;
  severity: Severity;
  mitreTactic: string;
  mitreTechnique: string;
  mitreId: string;
  conditions: string[];
  windowMinutes: number;
  triggerThreshold: number;
  isActive: boolean;
  matchedCount: number;
}

export interface DashboardStats {
  overallThreatScore: number; // 0-100 (weighted status of the network)
  activeIncidentsCount: number;
  processedEventsCount: number;
  criticalAlertsCount: number;
  uebaAnomalyCount: number;
  alertDistribution: Record<Severity, number>;
  eventsTimeline: { time: string; count: number; countCorrelated: number }[];
}
